# Generated by Django 4.1.3 on 2022-11-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Listing',
        ),
    ]
